name: music_streaming_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.2+1

environment:
  sdk: ">=3.0.0 <4.0.0" # Updated to support super-parameters

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  youtube_explode_dart: ^3.0.5
  just_audio: ^0.10.5
  just_audio_background: ^0.0.1-beta.11
  cloud_firestore: ^6.1.0
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.3
  connectivity_plus: ^6.1.3
  shared_preferences: ^2.2.2
  rxdart: ^0.28.0
  audio_video_progress_bar: ^2.0.1
  cached_network_image: ^3.3.1
  dio: ^5.4.1
  path_provider: ^2.1.2
  permission_handler: ^12.0.1
  file_picker: ^10.3.7
  device_info_plus: ^12.3.0
  http: ^1.2.0
  flutter_web_auth_2: ^4.0.0
  url_launcher: ^6.2.5
  audio_session: ^0.2.2
  internet_connection_checker: ^3.0.1
  on_audio_query: ^2.9.0
  collection: ^1.18.0
  share_plus: ^12.0.1
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0 # Added for animations
  glassmorphism: ^3.0.0 # Added for UI
  palette_generator: ^0.3.3+3 # Added for dynamic colors
  flutter_inappwebview: ^6.0.0
  crypto: ^3.0.7
  cast: 2.1.0 # Added for Chromecast support




  flutter_cache_manager: any

dependency_overrides:
  bonsoir: 5.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 21 # min supported by most apps now
  adaptive_icon_background: "#121212" # Dark background
  adaptive_icon_foreground: "assets/images/app_logo.png"